export const allCountryCodes = [
  ["AF", "Afghanistan"],
  ["AL", "Albania"],
  ["AQ", "Antarctica (the territory South of 60 deg S)"],
  ["DZ", "Algeria"],
  ["AS", "American Samoa"],
  ["AD", "Andorra"],
  ["AO", "Angola"],
  ["AG", "Antigua and Barbuda"],
  ["AZ", "Azerbaijan"],
  ["AZ", "Azerbaijan"],
  ["AR", "Argentina"],
  ["AU", "Australia"],
  ["AT", "Austria"],
  ["BS", "Bahamas"],
  ["BH", "Bahrain"],
  ["BD", "Bangladesh"],
  ["AM", "Armenia"],
  ["AM", "Armenia"],
  ["BB", "Barbados"],
  ["BE", "Belgium"],
  ["BM", "Bermuda"],
  ["BT", "Bhutan"],
  ["BO", "Bolivia"],
  ["BA", "Bosnia and Herzegovina"],
  ["BW", "Botswana"],
  ["BV", "Bouvet Island (Bouvetoya)"],
  ["BR", "Brazil"],
  ["BZ", "Belize"],
  ["IO", "British Indian Ocean Territory (Chagos Archipelago)"],
  ["SB", "Solomon Islands"],
  ["VG", "British Virgin Islands"],
  ["BN", "Brunei Darussalam"],
  ["BG", "Bulgaria"],
  ["MM", "Myanmar"],
  ["BI", "Burundi"],
  ["BY", "Belarus"],
  ["KH", "Cambodia"],
  ["CM", "Cameroon"],
  ["CA", "Canada"],
  ["CV", "Cape Verde"],
  ["KY", "Cayman Islands"],
  ["CF", "Central African Republic"],
  ["LK", "Sri Lanka"],
  ["TD", "Chad"],
  ["CL", "Chile"],
  ["CN", "China"],
  ["TW", "Taiwan"],
  ["CX", "Christmas Island"],
  ["CC", "Cocos (Keeling) Islands"],
  ["CO", "Colombia"],
  ["KM", "Comoros"],
  ["YT", "Mayotte"],
  ["CG", "Congo"],
  ["CD", "Congo"],
  ["CK", "Cook Islands"],
  ["CR", "Costa Rica"],
  ["HR", "Croatia"],
  ["CU", "Cuba"],
  ["CY", "Cyprus"],
  ["CY", "Cyprus"],
  ["CZ", "Czech Republic"],
  ["BJ", "Benin"],
  ["DK", "Denmark"],
  ["DM", "Dominica"],
  ["DO", "Dominican Republic"],
  ["EC", "Ecuador"],
  ["SV", "El Salvador"],
  ["GQ", "Equatorial Guinea"],
  ["ET", "Ethiopia"],
  ["ER", "Eritrea"],
  ["EE", "Estonia"],
  ["FO", "Faroe Islands"],
  ["FK", "Falkland Islands (Malvinas)"],
  ["GS", "South Georgia and the South Sandwich Islands"],
  ["FJ", "Fiji"],
  ["FI", "Finland"],
  ["AX", "Ãƒâ€¦land Islands"],
  ["FR", "France"],
  ["GF", "French Guiana"],
  ["PF", "French Polynesia"],
  ["TF", "French Southern Territories"],
  ["DJ", "Djibouti"],
  ["GA", "Gabon"],
  ["GE", "Georgia"],
  ["GE", "Georgia"],
  ["GM", "Gambia"],
  ["PS", "Palestinian Territory"],
  ["DE", "Germany"],
  ["GH", "Ghana"],
  ["GI", "Gibraltar"],
  ["KI", "Kiribati"],
  ["GR", "Greece"],
  ["GL", "Greenland"],
  ["GD", "Grenada"],
  ["GP", "Guadeloupe"],
  ["GU", "Guam"],
  ["GT", "Guatemala"],
  ["GN", "Guinea"],
  ["GY", "Guyana"],
  ["HT", "Haiti"],
  ["HM", "Heard Island and McDonald Islands"],
  ["VA", "Holy See (Vatican City State)"],
  ["HN", "Honduras"],
  ["HK", "Hong Kong"],
  ["HU", "Hungary"],
  ["IS", "Iceland"],
  ["IN", "India"],
  ["ID", "Indonesia"],
  ["IR", "Iran"],
  ["IQ", "Iraq"],
  ["IE", "Ireland"],
  ["IL", "Israel"],
  ["IT", "Italy"],
  ["CI", "Cote d'Ivoire"],
  ["JM", "Jamaica"],
  ["JP", "Japan"],
  ["KZ", "Kazakhstan"],
  ["KZ", "Kazakhstan"],
  ["JO", "Jordan"],
  ["KE", "Kenya"],
  ["KP", "Korea"],
  ["KR", "Korea"],
  ["KW", "Kuwait"],
  ["KG", "Kyrgyz Republic"],
  ["LA", "Lao People's Democratic Republic"],
  ["LB", "Lebanon"],
  ["LS", "Lesotho"],
  ["LV", "Latvia"],
  ["LR", "Liberia"],
  ["LY", "Libyan Arab Jamahiriya"],
  ["LI", "Liechtenstein"],
  ["LT", "Lithuania"],
  ["LU", "Luxembourg"],
  ["MO", "Macao"],
  ["MG", "Madagascar"],
  ["MW", "Malawi"],
  ["MY", "Malaysia"],
  ["MV", "Maldives"],
  ["ML", "Mali"],
  ["MT", "Malta"],
  ["MQ", "Martinique"],
  ["MR", "Mauritania"],
  ["MU", "Mauritius"],
  ["MX", "Mexico"],
  ["MC", "Monaco"],
  ["MN", "Mongolia"],
  ["MD", "Moldova"],
  ["ME", "Montenegro"],
  ["MS", "Montserrat"],
  ["MA", "Morocco"],
  ["MZ", "Mozambique"],
  ["OM", "Oman"],
  ["NA", "Namibia"],
  ["NR", "Nauru"],
  ["NP", "Nepal"],
  ["NL", "Netherlands"],
  ["AN", "Netherlands Antilles"],
  ["CW", "CuraÃƒÂ§ao"],
  ["AW", "Aruba"],
  ["SX", "Sint Maarten (Netherlands)"],
  ["BQ", "Bonaire"],
  ["NC", "New Caledonia"],
  ["VU", "Vanuatu"],
  ["NZ", "New Zealand"],
  ["NI", "Nicaragua"],
  ["NE", "Niger"],
  ["NG", "Nigeria"],
  ["NU", "Niue"],
  ["NF", "Norfolk Island"],
  ["NO", "Norway"],
  ["MP", "Northern Mariana Islands"],
  ["UM", "United States Minor Outlying Islands"],
  ["UM", "United States Minor Outlying Islands"],
  ["FM", "Micronesia"],
  ["MH", "Marshall Islands"],
  ["PW", "Palau"],
  ["PK", "Pakistan"],
  ["PA", "Panama"],
  ["PG", "Papua New Guinea"],
  ["PY", "Paraguay"],
  ["PE", "Peru"],
  ["PH", "Philippines"],
  ["PN", "Pitcairn Islands"],
  ["PL", "Poland"],
  ["PT", "Portugal"],
  ["GW", "Guinea-Bissau"],
  ["TL", "Timor-Leste"],
  ["PR", "Puerto Rico"],
  ["QA", "Qatar"],
  ["RE", "Reunion"],
  ["RO", "Romania"],
  ["RU", "Russian Federation"],
  ["RU", "Russian Federation"],
  ["RW", "Rwanda"],
  ["BL", "Saint Barthelemy"],
  ["SH", "Saint Helena"],
  ["KN", "Saint Kitts and Nevis"],
  ["AI", "Anguilla"],
  ["LC", "Saint Lucia"],
  ["MF", "Saint Martin"],
  ["PM", "Saint Pierre and Miquelon"],
  ["VC", "Saint Vincent and the Grenadines"],
  ["SM", "San Marino"],
  ["ST", "Sao Tome and Principe"],
  ["SA", "Saudi Arabia"],
  ["SN", "Senegal"],
  ["RS", "Serbia"],
  ["SC", "Seychelles"],
  ["SL", "Sierra Leone"],
  ["SG", "Singapore"],
  ["SK", "Slovakia (Slovak Republic)"],
  ["VN", "Vietnam"],
  ["SI", "Slovenia"],
  ["SO", "Somalia"],
  ["ZA", "South Africa"],
  ["ZW", "Zimbabwe"],
  ["ES", "Spain"],
  ["SS", "South Sudan"],
  ["EH", "Western Sahara"],
  ["SD", "Sudan"],
  ["SR", "Suriname"],
  ["SJ", "Svalbard & Jan Mayen Islands"],
  ["SZ", "Swaziland"],
  ["SE", "Sweden"],
  ["CH", "Switzerland"],
  ["SY", "Syrian Arab Republic"],
  ["TJ", "Tajikistan"],
  ["TH", "Thailand"],
  ["TG", "Togo"],
  ["TK", "Tokelau"],
  ["TO", "Tonga"],
  ["TT", "Trinidad and Tobago"],
  ["AE", "United Arab Emirates"],
  ["TN", "Tunisia"],
  ["TR", "Turkey"],
  ["TR", "Turkey"],
  ["TM", "Turkmenistan"],
  ["TC", "Turks and Caicos Islands"],
  ["TV", "Tuvalu"],
  ["UG", "Uganda"],
  ["UA", "Ukraine"],
  ["MK", "Macedonia"],
  ["EG", "Egypt"],
  ["GB", "United Kingdom of Great Britain & Northern Ireland"],
  ["GG", "Guernsey"],
  ["JE", "Jersey"],
  ["IM", "Isle of Man"],
  ["TZ", "Tanzania"],
  ["US", "United States of America"],
  ["VI", "United States Virgin Islands"],
  ["BF", "Burkina Faso"],
  ["UY", "Uruguay"],
  ["UZ", "Uzbekistan"],
  ["VE", "Venezuela"],
  ["WF", "Wallis and Futuna"],
  ["WS", "Samoa"],
  ["YE", "Yemen"],
  ["ZM", "Zambia"],
  ["XE", "Iraq-Saudi Arabia Neutral Zone"],
  ["XD", "United Nations Neutral Zone"],
  ["XS", "Spratly Islands"],
];

export const countryCntCodes = [
  ["AF", "AS"],
  ["AL", "EU"],
  ["AQ", "AN"],
  ["DZ", "AF"],
  ["AS", "OC"],
  ["AD", "EU"],
  ["AO", "AF"],
  ["AG", "NA"],
  ["AZ", "EU"],
  ["AZ", "AS"],
  ["AR", "SA"],
  ["AU", "OC"],
  ["AT", "EU"],
  ["BS", "NA"],
  ["BH", "AS"],
  ["BD", "AS"],
  ["AM", "EU"],
  ["AM", "AS"],
  ["BB", "NA"],
  ["BE", "EU"],
  ["BM", "NA"],
  ["BT", "AS"],
  ["BO", "SA"],
  ["BA", "EU"],
  ["BW", "AF"],
  ["BV", "AN"],
  ["BR", "SA"],
  ["BZ", "NA"],
  ["IO", "AS"],
  ["SB", "OC"],
  ["VG", "NA"],
  ["BN", "AS"],
  ["BG", "EU"],
  ["MM", "AS"],
  ["BI", "AF"],
  ["BY", "EU"],
  ["KH", "AS"],
  ["CM", "AF"],
  ["CA", "NA"],
  ["CV", "AF"],
  ["KY", "NA"],
  ["CF", "AF"],
  ["LK", "AS"],
  ["TD", "AF"],
  ["CL", "SA"],
  ["CN", "AS"],
  ["TW", "AS"],
  ["CX", "AS"],
  ["CC", "AS"],
  ["CO", "SA"],
  ["KM", "AF"],
  ["YT", "AF"],
  ["CG", "AF"],
  ["CD", "AF"],
  ["CK", "OC"],
  ["CR", "NA"],
  ["HR", "EU"],
  ["CU", "NA"],
  ["CY", "EU"],
  ["CY", "AS"],
  ["CZ", "EU"],
  ["BJ", "AF"],
  ["DK", "EU"],
  ["DM", "NA"],
  ["DO", "NA"],
  ["EC", "SA"],
  ["SV", "NA"],
  ["GQ", "AF"],
  ["ET", "AF"],
  ["ER", "AF"],
  ["EE", "EU"],
  ["FO", "EU"],
  ["FK", "SA"],
  ["GS", "AN"],
  ["FJ", "OC"],
  ["FI", "EU"],
  ["AX", "EU"],
  ["FR", "EU"],
  ["GF", "SA"],
  ["PF", "OC"],
  ["TF", "AN"],
  ["DJ", "AF"],
  ["GA", "AF"],
  ["GE", "EU"],
  ["GE", "AS"],
  ["GM", "AF"],
  ["PS", "AS"],
  ["DE", "EU"],
  ["GH", "AF"],
  ["GI", "EU"],
  ["KI", "OC"],
  ["GR", "EU"],
  ["GL", "NA"],
  ["GD", "NA"],
  ["GP", "NA"],
  ["GU", "OC"],
  ["GT", "NA"],
  ["GN", "AF"],
  ["GY", "SA"],
  ["HT", "NA"],
  ["HM", "AN"],
  ["VA", "EU"],
  ["HN", "NA"],
  ["HK", "AS"],
  ["HU", "EU"],
  ["IS", "EU"],
  ["IN", "AS"],
  ["ID", "AS"],
  ["IR", "AS"],
  ["IQ", "AS"],
  ["IE", "EU"],
  ["IL", "AS"],
  ["IT", "EU"],
  ["CI", "AF"],
  ["JM", "NA"],
  ["JP", "AS"],
  ["KZ", "EU"],
  ["KZ", "AS"],
  ["JO", "AS"],
  ["KE", "AF"],
  ["KP", "AS"],
  ["KR", "AS"],
  ["KW", "AS"],
  ["KG", "AS"],
  ["LA", "AS"],
  ["LB", "AS"],
  ["LS", "AF"],
  ["LV", "EU"],
  ["LR", "AF"],
  ["LY", "AF"],
  ["LI", "EU"],
  ["LT", "EU"],
  ["LU", "EU"],
  ["MO", "AS"],
  ["MG", "AF"],
  ["MW", "AF"],
  ["MY", "AS"],
  ["MV", "AS"],
  ["ML", "AF"],
  ["MT", "EU"],
  ["MQ", "NA"],
  ["MR", "AF"],
  ["MU", "AF"],
  ["MX", "NA"],
  ["MC", "EU"],
  ["MN", "AS"],
  ["MD", "EU"],
  ["ME", "EU"],
  ["MS", "NA"],
  ["MA", "AF"],
  ["MZ", "AF"],
  ["OM", "AS"],
  ["NA", "AF"],
  ["NR", "OC"],
  ["NP", "AS"],
  ["NL", "EU"],
  ["AN", "NA"],
  ["CW", "NA"],
  ["AW", "NA"],
  ["SX", "NA"],
  ["BQ", "NA"],
  ["NC", "OC"],
  ["VU", "OC"],
  ["NZ", "OC"],
  ["NI", "NA"],
  ["NE", "AF"],
  ["NG", "AF"],
  ["NU", "OC"],
  ["NF", "OC"],
  ["NO", "EU"],
  ["MP", "OC"],
  ["UM", "OC"],
  ["UM", "NA"],
  ["FM", "OC"],
  ["MH", "OC"],
  ["PW", "OC"],
  ["PK", "AS"],
  ["PA", "NA"],
  ["PG", "OC"],
  ["PY", "SA"],
  ["PE", "SA"],
  ["PH", "AS"],
  ["PN", "OC"],
  ["PL", "EU"],
  ["PT", "EU"],
  ["GW", "AF"],
  ["TL", "AS"],
  ["PR", "NA"],
  ["QA", "AS"],
  ["RE", "AF"],
  ["RO", "EU"],
  ["RU", "EU"],
  ["RU", "AS"],
  ["RW", "AF"],
  ["BL", "NA"],
  ["SH", "AF"],
  ["KN", "NA"],
  ["AI", "NA"],
  ["LC", "NA"],
  ["MF", "NA"],
  ["PM", "NA"],
  ["VC", "NA"],
  ["SM", "EU"],
  ["ST", "AF"],
  ["SA", "AS"],
  ["SN", "AF"],
  ["RS", "EU"],
  ["SC", "AF"],
  ["SL", "AF"],
  ["SG", "AS"],
  ["SK", "EU"],
  ["VN", "AS"],
  ["SI", "EU"],
  ["SO", "AF"],
  ["ZA", "AF"],
  ["ZW", "AF"],
  ["ES", "EU"],
  ["SS", "AF"],
  ["EH", "AF"],
  ["SD", "AF"],
  ["SR", "SA"],
  ["SJ", "EU"],
  ["SZ", "AF"],
  ["SE", "EU"],
  ["CH", "EU"],
  ["SY", "AS"],
  ["TJ", "AS"],
  ["TH", "AS"],
  ["TG", "AF"],
  ["TK", "OC"],
  ["TO", "OC"],
  ["TT", "NA"],
  ["AE", "AS"],
  ["TN", "AF"],
  ["TR", "EU"],
  ["TR", "AS"],
  ["TM", "AS"],
  ["TC", "NA"],
  ["TV", "OC"],
  ["UG", "AF"],
  ["UA", "EU"],
  ["MK", "EU"],
  ["EG", "AF"],
  ["GB", "EU"],
  ["GG", "EU"],
  ["JE", "EU"],
  ["IM", "EU"],
  ["TZ", "AF"],
  ["US", "NA"],
  ["VI", "NA"],
  ["BF", "AF"],
  ["UY", "SA"],
  ["UZ", "AS"],
  ["VE", "SA"],
  ["WF", "OC"],
  ["WS", "OC"],
  ["YE", "AS"],
  ["ZM", "AF"],
  ["XX", "OC"],
  ["XE", "AS"],
  ["XD", "AS"],
  ["XS", "AS"]
];

export const continentCodes = {
  WW: "Worldwide",
  AS: "Asia",
  EU: "Europe",
  NA: "North America",
  SA: "South America",
  AN: "Antarctica",
  AF: "Africa",
  OC: "Oceania",
};
function shuffleArray(array) {
  var clone = array;
  for (let i = clone.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [clone[i], clone[j]] = [clone[j], clone[i]];
  }
  return clone;
}

// function CSVToArray(strData, strDelimiter) {
//   strDelimiter = strDelimiter || ",";

//   var objPattern = new RegExp(
//     "(\\" +
//       strDelimiter +
//       "|\\r?\\n|\\r|^)" +
//       '(?:"([^"]*(?:""[^"]*)*)"|' +
//       '([^"\\' +
//       strDelimiter +
//       "\\r\\n]*))",
//     "gi"
//   );

//   var arrData = [[]];

//   var arrMatches = null;

//   while ((arrMatches = objPattern.exec(strData))) {
//     var strMatchedDelimiter = arrMatches[1];

//     if (strMatchedDelimiter.length && strMatchedDelimiter != strDelimiter) {
//       arrData.push([]);
//     }

//     if (arrMatches[2]) {
//       var strMatchedValue = arrMatches[2].replace(new RegExp('""', "g"), '"');
//     } else {
//       var strMatchedValue = arrMatches[3];
//     }

//     arrData[arrData.length - 1].push(strMatchedValue);
//   }
//   return arrData;
// }

export default shuffleArray;
